services:
  munaseq_db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: munaseq
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: munaseq_db
  munaseq_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:3002
    environment:
      DATABASE_URL: postgres://munaseq:1234@munaseq_db:5432/munaseq_db

networks:
  munaseq-network:
